name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./src/ajiva
      run: dotnet restore
    - name: Build
      working-directory: ./src/ajiva
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./src/ajiva.Test
      run: dotnet test --no-build --verbosity normal
