name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: ./src/Ajiva.Application
      run: dotnet restore
    - name: Build
      working-directory: ./src/Ajiva.Application
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./src/Ajiva.Test
      run: dotnet test --verbosity normal
